import {
  Archive,
  ArrowLeft,
  Banknote,
  BadgeDollarSign,
  Boxes,
  ContactRound,
  CreditCard,
  CircleCheck,
  CircleOff,
  CircleX,
  ClipboardList,
  Contact,
  FilePlus,
  Eye,
  Info,
  LayoutDashboard,
  LogOut,
  Package,
  PackagePlus,
  Pencil,
  Plus,
  Printer,
  RefreshCw,
  ReceiptText,
  Save,
  Search,
  ShieldCheck,
  Settings,
  ShoppingCart,
  Store,
  Trash2,
  TriangleAlert,
  Truck,
  UserCog,
  Users,
  X,
  type LucideIcon
} from 'lucide-react'

export const iconStroke = 2
export const iconSize = 20
export const iconSizeNav = 20
export const iconSizeStatus = 24

export const AppIcons = {
  dashboard: LayoutDashboard,
  employee: Users,
  items: Package,
  station: Store,
  stationInventory: Boxes,
  creditMonitoring: CreditCard,
  officialReceipt: ReceiptText,
  privilegeAssignment: UserCog,
  customerManagement: ContactRound,
  privilege: ShieldCheck,
  price: BadgeDollarSign,
  itemDelivery: PackagePlus,
  orders: ShoppingCart,
  consignee: Contact,
  consignment: ClipboardList,
  supplier: Truck,
  search: Search,
  add: Plus,
  edit: Pencil,
  delete: Trash2,
  save: Save,
  logout: LogOut,
  settings: Settings,
  success: CircleCheck,
  activate: CircleCheck,
  deactivate: CircleOff,
  view: Eye,
  warning: TriangleAlert,
  error: CircleX,
  info: Info,
  close: X,
  back: ArrowLeft,
  print: Printer,
  payment: Banknote,
  cashDrawer: Archive,
  refresh: RefreshCw,
  newOrder: FilePlus
} as const satisfies Record<string, LucideIcon>

export type AppIconName = keyof typeof AppIcons
